config/urls.py
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from django.views import defaults as default_views

from sterlingpos.users import views as users_views
from sterlingpos.dashboard import views as dashboard_views
from sterlingpos.core import views as core_views

from rest_framework_jwt.views import obtain_jwt_token
from sterlingpos.core.midtrans.views import MidtransNotificationHandlingView
from sterlingpos.integration.shopeepay.views import ShopeepayNotificationHandlingView


urlpatterns = [
    url(r"^$", RedirectView.as_view(url=reverse_lazy('dashboard')), name="home"),

    url(r'^accounts/signup/$', users_views.WizardUserSignUpView.as_view(), name='account_signup'),
    url(r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", users_views.EmailConfirmation.as_view(),
        name="account_confirm_email"),

    url(settings.ADMIN_URL, admin.site.urls),

    url(
        regex=r'^dashboard/$',
        view=dashboard_views.DashboardIndexView.as_view(),
        name='dashboard'
    ),
    url(
        regex=r'^dashboard/branch/(?P<branch_pk>[0-9]+)$',
        view=dashboard_views.DashboardIndexView.as_view(),
        name='dashboard'
    ),
    url(
        regex=r'^chart/$',
        view=dashboard_views.DashboardChartView.as_view(),
        name='dashboard-chart'
    ),
    url(
        regex=r'^chart/branch/(?P<branch_pk>[0-9]+)$',
        view=dashboard_views.DashboardChartView.as_view(),
        name='dashboard-chart'
    ),
    url(
        regex=r'^summary-chart/$',
        view=dashboard_views.DashboardSalesSummaryGroupView.as_view(),
        name='summary-chart'
    ),
    url(
        regex=r'^summary-chart/branch/(?P<branch_pk>[0-9]+)$',
        view=dashboard_views.DashboardSalesSummaryGroupView.as_view(),
        name='summary-chart'
    ),
    url(
        regex=r'^category-chart/$',
        view=dashboard_views.DashboardCategoryChartView.as_view(),
        name='dashboard-category-chart'
    ),
    url(
        regex=r'^category-chart/branch/(?P<branch_pk>[0-9]+)$',
        view=dashboard_views.DashboardCategoryChartView.as_view(),
        name='dashboard-category-chart'
    ),


    # User management
    url(
        r"^settings/users/",
        include("sterlingpos.users.urls", namespace="users"),
    ),
    url(
        r"^settings/accounts/",
        include("sterlingpos.accounts.urls", namespace="accounts"),
    ),
    url(
        r"^settings/subscription/",
        include("sterlingpos.subscription.urls", namespace="subscription"),
    ),
    url(
        r"^cash-balance/",
        include("sterlingpos.cash_balance.urls", namespace="cash_balance"),
    ),
    url(
        r"^sales/",
        include("sterlingpos.sales.urls", namespace="sales"),
    ),
    url(
        r"^stocks/",
        include("sterlingpos.stocks.urls", namespace="stocks"),
    ),
    url(
        r"^library/promo/",
        include("sterlingpos.promo.urls", namespace="promo"),
    ),
    url(
        r"^library/",
        include("sterlingpos.catalogue.urls", namespace="catalogue"),
    ),
    url(
        r"^device/",
        include("sterlingpos.device.urls", namespace="device"),
    ),
    url(
        r"^private-apps/",
        include("sterlingpos.private_apps.urls", namespace="private-apps"),
    ),
    url(
        r"^table-management/",
        include(
            "sterlingpos.table_management.urls", namespace="table_management"),
    ),
    url(
        r"^table-order/",
        include(
            "sterlingpos.table_order.urls", namespace="table_order"),
    ),
    url(
        r"^role/",
        include(
            "sterlingpos.role.urls", namespace="role"),
    ),
    url(
        r"^waiters/",
        include("sterlingpos.waiters.urls", namespace="waiters"),
    ),
    url(
        r"^kitchen-display/",
        include(
            "sterlingpos.kitchen_display.urls", namespace="kitchen_display"),
    ),
    url(
        r"^settings/",
        include("sterlingpos.outlet.urls", namespace="outlet"),
    ),
    url(
        r"^settings/receipt/",
        include("sterlingpos.receipt.urls", namespace="receipt"),
    ),
    url(
        r"^settings/surcharges/",
        include("sterlingpos.surcharges.urls", namespace="surcharges"),
    ),
    url(
        r"^customers/",
        include("sterlingpos.customer.urls", namespace="customers"),
    ),
    url(
        r"^digital-payment/",
        include("sterlingpos.digital_payment.urls", namespace="digital_payment"),
    ),
    url(
        r"^productions/",
        include("sterlingpos.productions.urls", namespace="productions")
    ),

    url(
        r"^notification/",
        include("sterlingpos.notification.urls", namespace="notification")
    ),


    url(
        regex=r'^formset/$',
        view=core_views.UpdateFormset.as_view(),
        name='formset_update'
    ),

    url(r"^accounts/", include("allauth.urls")),

    url(r'^invitations/', include('sterlingpos.users.invitation_urls', namespace='invitation')),
    url(r'^accounts/invitations/send-invite/complete/$', users_views.SendInviteComplete.as_view(),
        name='send-invite-complete'),
    url(r'^accounts/invitations/send-invite/$', users_views.SendInvite.as_view(),
        name='send-invite'),
    url(r'^accounts/invitations/register/$', users_views.InviteeRegistration.as_view(),
        name='invitee-registration'),
    url(r'^accounts/invitations/register/success/$', users_views.InviteeRegistrationComplete.as_view(),
        name='invitee-registration-success'),

    url(r'^accounts/invitations/accept-invite/(?P<key>\w+)/?$', users_views.AcceptInvite.as_view(),
        name='accept-invite'),

    url(r'^accounts/invitations/delete/$', users_views.UserInvitationDeleteView.as_view(),
        name='invitation-delete'),

    url(r'^accounts/invitations/', include('invitations.urls', namespace='invitations')),

    url(r"^api-token-auth/", obtain_jwt_token),

    url(r'^midtrans/notification/handling/$', MidtransNotificationHandlingView.as_view(), name="veritrans_notification"),
    url(r'^callback/shopeepay/$', ShopeepayNotificationHandlingView.as_view(), name="shoopepay_notification"),

    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v2/', include('sterlingpos.api.urls_2', namespace='v2')),
    url(r'^api/v2.1/', include('sterlingpos.api.urls_2_1', namespace='v2.1')),


    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if "silk" in settings.INSTALLED_APPS:
    urlpatterns = [url(r'^silk/', include('silk.urls', namespace='silk'))] + urlpatterns


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

sterlingpos/promo/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

app_name = 'promo'
urlpatterns = [
    url(regex=r'^$', view=views.PromoListView.as_view(),
        name='promo_list'),
    url(regex=r'^data$', view=views.PromoListJson.as_view(),
        name='data_promo'),
    url(regex=r'^create/$', view=views.PromoCreateView.as_view(),
        name='promo_create'),

    url(r'^deactive/$', views.PromoDeactiveJson.as_view(),
        name='promo_deactive'),
    url(r'^activate/$', views.PromoActivateJson.as_view(),
        name='promo_activate'),
    url(r'^delete/$', views.PromoDeleteJson.as_view(),
        name='promo_delete'),
    url(regex=r'^edit/(?P<pk>\d+)/$', view=views.PromoUpdateView.as_view(),
        name='promo_update'),
    url(regex=r'^promo-tag/autocomplete/$', view=views.PromoTagAutoCompleteView.as_view(create_field='value'),
        name='promo_tag_autocomplete'),

    url(regex=r'^employee/$', view=views.EmployeePromoListView.as_view(),
        name='employee_promo_list'),
    url(regex=r'^employee/data$', view=views.EmployeePromoListJson.as_view(),
        name='employee_promo_data'),
    url(regex=r'^employee/create/$', view=views.EmployeePromoCreateView.as_view(),
        name='employee_promo_create'),
    url(regex=r'^employee/edit/(?P<pk>\d+)/$', view=views.EmployeePromoUpdateView.as_view(),
        name='employee_promo_update'),

    url(regex=r'^usages/data/$', view=views.PromoUsageReportListJson.as_view(),
        name='data_promo_usages'),
    url(regex=r'^usages/outlet/(?P<outlet_id>\d+)/data/$', view=views.PromoUsageReportListJson.as_view(),
        name='data_promo_usages'),
    url(regex=r'^usages/$', view=views.PromoUsageReportView.as_view(),
        name='promo_usages'),
    url(regex=r'^usages/(?P<promo_id>\d+)/data/$', view=views.PromoUsageListJson.as_view(),
        name='data_promo_usages_list'),
    url(regex=r'^usages/(?P<promo_id>\d+)/outlet/(?P<outlet_id>\d+)/data/$', view=views.PromoUsageListJson.as_view(),
        name='data_promo_usages_list'),
    url(regex=r'^usages/(?P<promo_id>\d+)/$', view=views.PromoUsageListView.as_view(),
        name='promo_usages_list'),
    url(regex=r'^usages/(?P<promo_id>\d+)/outlet/(?P<outlet_id>\d+)/$', view=views.PromoUsageListView.as_view(),
        name='promo_usages_list'),
]

sterlingpos/role/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


app_name = 'role'
urlpatterns = [
    url(r'^$', views.RoleListView.as_view(),
        name='list'),
    url(r'^(?P<pk>\d+)/$', views.RoleUpdateView.as_view(),
        name='update'),
    url(r'^delete/$', views.RoleDeleteView.as_view(),
        name='delete'),
    url(r'^create/$', views.RoleCreateView.as_view(),
        name='create'),
    url(r'^settings/$', views.RoleSettingUpdateView.as_view(),
        name='settings'),

    url(r'^data/$', views.RoleListJsonView.as_view(),
        name='data'),
]

sterlingpos/sales/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

app_name = "sales"
urlpatterns = [
    url(regex=r'^sales-summary/$', view=views.SalesSummaryTemplateView.as_view(),
        name='sales_summary'),
    url(regex=r'^sales-summary/outlet/(?P<outlet_pk>\d+)$', view=views.SalesSummaryTemplateView.as_view(),
        name='sales_summary'),

    url(regex=r'^gross-profit/$', view=views.GrossProfitTemplateView.as_view(),
        name='gross_profit'),
    url(regex=r'^gross-profit/outlet/(?P<outlet_pk>\d+)$', view=views.GrossProfitTemplateView.as_view(),
        name='gross_profit'),
    url(regex=r'^gross-profit/(?P<detail>month|date|days|hours)/$', view=views.GrossProfitTemplateView.as_view(),
       name='gross_profit'),
    url(regex=r'^gross-profit/outlet/(?P<outlet_pk>\d+)/(?P<detail>month|date|days|hours)/$', view=views.GrossProfitTemplateView.as_view(),
        name='gross_profit'), 

    url(regex=r'^sales-report/$', view=views.SalesReportTemplateView.as_view(),
       name='sales_report'),
    url(regex=r'^sales-report/outlet/(?P<outlet_pk>\d+)$', view=views.SalesReportTemplateView.as_view(),
        name='sales_report'), 
    url(regex=r'^sales-report/(?P<detail>month|date|days|hours)/$', view=views.SalesReportTemplateView.as_view(),
       name='sales_report'),
    url(regex=r'^sales-report/outlet/(?P<outlet_pk>\d+)/(?P<detail>month|date|days|hours)/$', view=views.SalesReportTemplateView.as_view(),
        name='sales_report'), 

    url(regex=r'^sales-by-category/$', view=views.SalesByCategoryTemplateView.as_view(),
        name='sales_by_category'),
    url(regex=r'^sales-by-category/outlet/(?P<outlet_pk>\d+)$', view=views.SalesByCategoryTemplateView.as_view(),
        name='sales_by_category'),

    url(regex=r'^sales-by-order-type/$', view=views.SalesByOrderTypeTemplateView.as_view(),
        name='sales_by_order_type'),
    url(regex=r'^sales-by-order-type/outlet/(?P<outlet_pk>\d+)/$', view=views.SalesByOrderTypeTemplateView.as_view(),
        name='sales_by_order_type'),
    url(regex=r'^sales-by-order-type/(?P<detail>month|date|days|hours)/$', view=views.SalesByOrderTypeTemplateView.as_view(),
        name='sales_by_order_type'),
    url(regex=r'^sales-by-order-type/outlet/(?P<outlet_pk>\d+)/(?P<detail>month|date|days|hours)/$', view=views.SalesByOrderTypeTemplateView.as_view(),
        name='sales_by_order_type'),

    url(regex=r'^sales-by-payment/$', view=views.SalesByPaymentTemplateView.as_view(),
        name='sales_by_payment'),
    url(regex=r'^sales-by-payment/outlet/(?P<outlet_pk>\d+)$', view=views.SalesByPaymentTemplateView.as_view(),
        name='sales_by_payment'),

    url(regex=r'^sales-by-type/$', view=views.SalesByTransactionTypeTemplateView.as_view(),
        name='sales_by_type'),
    url(regex=r'^sales-by-type/outlet/(?P<outlet_pk>\d+)$', view=views.SalesByTransactionTypeTemplateView.as_view(),
        name='sales_by_type'),
    url(regex=r'^sales-by-type/(?P<outlet_pk>[0-9]+)/data/$', view=views.SalesByTransactionTypeListJson.as_view(),
        name='sales_by_type_data'),
    url(regex=r'^sales-by-type/data/$', view=views.SalesByTransactionTypeListJson.as_view(),
        name='sales_by_type_data'),

    url(regex=r'^sales-order/$', view=views.SalesOrderListView.as_view(),
        name='sales_order_list'),
    url(regex=r'^sales-order/(?P<pk>\d+)/$', view=views.SalesOrderDetailView.as_view(),
        name='sales_order_detail'),
    url(regex=r'^sales-order/data/$', view=views.SalesOrderListJson.as_view(),
        name='sales_order_data'),

    url(regex=r'^invoice/$', view=views.InvoiceListView.as_view(),
        name='invoice_list'),
    url(regex=r'^invoice/data/$', view=views.InvoiceListJson.as_view(),
        name='invoice_data'),
    url(regex=r'^invoice/(?P<pk>\d+)/$', view=views.InvoiceDetailView.as_view(),
        name='invoice_detail'),
    url(regex=r'^invoice/(?P<invoice_pk>\d+)/payments/data/$', view=views.PaymentDetailListJson.as_view(),
        name='invoice_payment_list'),
    url(regex=r'^invoice/(?P<invoice_pk>\d+)/payments/create/$',
        view=views.PaymentDetailCreateView.as_view(),
        name='invoice_payment_create'),

    url(regex=r'^invoice_installment/$', view=views.InvoiceInstallmentListView.as_view(),
        name='invoice_installment_list'),
    url(regex=r'^invoice_installment/data/$', view=views.InvoiceInstallmentListJson.as_view(),
        name='invoice_installment_data'),
    url(regex=r'^invoice_installment/(?P<pk>\d+)/$', view=views.InvoiceInstallmentDetailView.as_view(),
        name='invoice_installment_detail'),
    url(regex=r'^invoice_installment/(?P<installment_pk>\d+)/payments/data/$', view=views.InstallmentPaymentDetailListJson.as_view(),
        name='invoice_installment_payment_list'),
    url(regex=r'^invoice_installment/(?P<installment_pk>\d+)/payments/create/$',
        view=views.InstallmentPaymentDetailCreateView.as_view(),
        name='invoice_installment_payment_create'),

    url(regex=r'^payment/(?P<pk>\d+)/$', view=views.PaymentDetailListJson.as_view(),
        name='payment_detail'),


    url(regex=r'^sales-order-option/$', view=views.SalesOrderOptionListView.as_view(),
        name='sales_order_option_list'),
    url(regex=r'^sales-order-option/create/$', view=views.SalesOrderOptionCreateView.as_view(),
        name='sales_order_option_create'),
    url(regex=r'^sales-order-option/(?P<pk>\d+)/$', view=views.SalesOrderOptionUpdateView.as_view(),
        name='sales_order_option_edit'),
    url(regex=r'^sales-order-option/delete/$', view=views.SalesOrderOptionDeleteView.as_view(),
        name='sales_order_option_delete'),
    url(regex=r'^sales-order-option/data/$', view=views.SalesOrderOptionListJson.as_view(),
        name='sales_order_option_data'),

    url(regex=r'^product-order/$', view=views.ProductOrderListView.as_view(),
        name='product_order_list'),
    url(regex=r'^product-order/data/$', view=views.ProductOrderListJson.as_view(),
        name='data_product_order'),

    url(regex=r'^product-sales/$', view=views.ProductSalesListView.as_view(),
        name='product_sales_list'),
    url(regex=r'^product-sales/data/$', view=views.ProductSalesListJson.as_view(),
        name='data_product_sales'),
    url(regex=r'^product-sales/branch/(?P<outlet_pk>[0-9]+)$', view=views.ProductSalesListJson.as_view(),
        name='data_product_sales'),

    url(regex=r'^addon-sales/$', view=views.ProductAddonSalesListView.as_view(),
        name='product_addon_sales_list'),
    url(regex=r'^addon-sales/data/$', view=views.ProductAddonSalesListJson.as_view(),
        name='data_product_addon_sales'),
    url(regex=r'^addon-sales/branch/(?P<outlet_pk>[0-9]+)$', view=views.ProductAddonSalesListJson.as_view(),
        name='data_product_addon_sales'),

    url(regex=r'^payment-method/$', view=views.EnabledPaymentMethodUpdateView.as_view(),
        name='payment_method_update'),
    url(regex=r'^payment-method/autocomplete/$', view=views.PaymentMethodAutoCompleteView.as_view(),
        name='payment_method_autocomplete'),
    url(regex=r'^payment-method/all/autocomplete/$', view=views.AllPaymentMethodAutoCompleteView.as_view(),
        name='all_payment_method_autocomplete'),
        

    url(regex=r'^settings/$', view=views.SalesReportSettingsUpdateView.as_view(),
        name='settings'),
    url(regex=r'^settings/data/$', view=views.SalesReportSettingInitialView.as_view(),
        name='settings_data'),

    url(regex=r'^cashier-activity/$', view=views.CashierActivityListView.as_view(),
        name='cashier_activity_list'),
    url(regex=r'^cashier-activity/data/$', view=views.CashierActivityListJson.as_view(),
        name='cashier_activity_data'),

    url(regex=r'^cashier-activity/reasons/$', view=views.CashierActivityReasonListView.as_view(),
        name='cashier_activity_reason_list'),
    url(regex=r'^cashier-activity/reasons/data/$', view=views.CashierActivityReasonListJson.as_view(),
        name='cashier_activity_reason_data'),
    url(regex=r'^cashier-activity/reasons/create/$', view=views.CashierActivityReasonCreateView.as_view(),
        name='cashier_activity_reason_create'),
    url(regex=r'^cashier-activity/reasons/delete/$', view=views.CashierActivityReasonDeleteView.as_view(),
        name='cashier_activity_reason_delete'),
    url(regex=r'^cashier-activity/reasons/(?P<pk>\d+)/$', view=views.CashierActivityReasonUpdateView.as_view(),
        name='cashier_activity_reason_update'),

    url(regex=r'^transaction-type/reasons/$',
        view=views.TransactionTypeReasonListView.as_view(),
        name='transaction_type_reason_list'),
    url(regex=r'^transaction-type/reasons/data/$',
        view=views.TransactionTypeReasonListJson.as_view(),
        name='transaction_type_reason_data'),
    url(regex=r'^transaction-type/reasons/create/$',
        view=views.TransactionTypeReasonCreateView.as_view(),
        name='transaction_type_reason_create'),
    url(regex=r'^transaction-type/reasons/delete/$',
        view=views.TransactionTypeReasonDeleteView.as_view(),
        name='transaction_type_reason_delete'),
    url(regex=r'^transaction-type/reasons/(?P<pk>\d+)/$',
        view=views.TransactionTypeReasonUpdateView.as_view(),
        name='transaction_type_reason_update'),

    url(r'^transaction-type/reasons/archive/$',
        view=views.TransactionTypeReasonArchiveView.as_view(),
        name='transaction_type_reason_archive'),
    url(r'^transaction-type/reasons/activate/$',
        view=views.TransactionTypeReasonActivateView.as_view(),
        name='transaction_type_reason_activate'),

]

sterlingpos/templates/dashboard/kitchen_display/kitchen_card_item_list.html
{% extends "dashboard/base_datatable.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Kitchen Display" %}{% endblock %}

{% block applications_active_class %}active{% endblock %}
{% block mobile_applications_active_class %}active{% endblock %}
{% block secondary_sidebar_expand %}expand{% endblock %}
{% block secondary_sidebar_applications_show %}show{% endblock %}
{% block applications_kitchen_display_class %}submenu-active{% endblock %}
{% block mobile_applications_kitchen_display_class %}submenu-active{% endblock %}

{% block tab_div_class %}fixed-header-tab{% endblock %}
{% block content_class %}col-12 p-0 fixed-tab-content{% endblock %}
{% block tab_div_style %}background: white; border-bottom: 1px solid #d7d7db;{% endblock %}
{% block tab_section_style %}border-bottom: 1px solid #d7d7db;{% endblock %}
{% block action_div_style %}background: white; border-top: 1px solid #d7d7db;{% endblock %}
{% block datatable_title %}{% trans "Kitchen Display" %}{% endblock datatable_title %}

{% block tab_list %}
  <ul class="nav nav-tabs pt-2" id="myTab">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'kitchen_display:settings' %}">{% trans "Settings" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'kitchen_display:settings_outlet' %}">{% trans "Outlet" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'kitchen_display:list' %}">{% trans "Kitchen Card Item" %}</a>
    </li>
  </ul>
{% endblock %}
{% block datatable_id %}tbl_product{% endblock datatable_id %}

{% block datatable_thead_tr %}
  <th>{% trans 'Product' %}</th>
  <th>{% trans 'Created At' %}</th>
  <th>{% trans 'Cooked At' %}</th>
  <th>{% trans 'Finished At' %}</th>
  <th>{% trans 'Void At' %}</th>
{% endblock datatable_thead_tr %}

{% block datatable_filter %}
<tr class='datatable-filter'>
  <td>
    <div class="datatable-filter-input-group input-group mtm">
      <input type="text" class="form-control extra-table-control clearable" placeholder="{% trans 'Search...' %}">
    </div>
  </td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
</tr>
{% endblock datatable_filter %}

{% block javascript %}
{{ block.super }}
<script>
  $(document).ready(function () {
    base_url = "{% url 'kitchen_display:item_data' pk %}";

    tableOptions = {
      pageLength: 25,
      columnDefs: [
        {targets: 'no-sort', orderable: false},
        {targets: 'text-center',  className: 'text-center'},
      ],
    }

  });
</script>
<script type="text/javascript" src="{% static 'js/datatable-config.js' %}"></script>

{% endblock %}

sterlingpos/templates/dashboard/kitchen_display/kitchen_card_list.html
{% extends "dashboard/base_datatable.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Kitchen Display" %}{% endblock %}

{% block applications_active_class %}active{% endblock %}
{% block mobile_applications_active_class %}active{% endblock %}
{% block secondary_sidebar_expand %}expand{% endblock %}
{% block secondary_sidebar_applications_show %}show{% endblock %}
{% block applications_kitchen_display_class %}submenu-active{% endblock %}
{% block mobile_applications_kitchen_display_class %}submenu-active{% endblock %}

{% block tab_div_class %}fixed-header-tab{% endblock %}
{% block content_class %}col-12 p-0 fixed-tab-content{% endblock %}
{% block tab_div_style %}background: white; border-bottom: 1px solid #d7d7db;{% endblock %}
{% block tab_section_style %}border-bottom: 1px solid #d7d7db;{% endblock %}
{% block action_div_style %}background: white; border-top: 1px solid #d7d7db;{% endblock %}
{% block datatable_title %}{% trans "Kitchen Display" %}{% endblock datatable_title %}

{% block tab_list %}
  <ul class="nav nav-tabs pt-2" id="myTab">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'kitchen_display:settings' %}">{% trans "Settings" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'kitchen_display:settings_outlet' %}">{% trans "Outlet" %}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="#">{% trans "Kitchen Card" %}</a>
    </li>
  </ul>
{% endblock %}
{% block datatable_id %}tbl_product{% endblock datatable_id %}

{% block date_range %}
<div id="filters" class="mb-3">
  {% include "partials/datatable_filters.html" with view_name="kitchen_display:data" %}
</div>
{% endblock %}

{% block datatable_thead_tr %}
  <th>{% trans 'Code' %}</th>
  <th>{% trans 'Outlet' %}</th>
  <th>{% trans 'Start Date' %}</th>
  <th>{% trans 'End Date' %}</th>
  <th>{% trans 'Duration' %}</th>
  <th>{% trans 'Void at' %}</th>
{% endblock datatable_thead_tr %}

{% block datatable_filter %}
<tr class='datatable-filter'>
  <td>
    <div class="datatable-filter-input-group input-group mtm">
      <input type="text" class="form-control extra-table-control clearable" placeholder="{% trans 'Search...' %}">
    </div>
  </td>
  <td></td>
  <td></td>
  <td></td>
  <td>
    <div class="datatable-filter-input-group input-group mtm">
      <input type="text" class="form-control extra-table-control clearable" placeholder="{% trans 'Search...' %}">
    </div>
  </td>
  <td></td>
</tr>
{% endblock datatable_filter %}

{% block javascript %}
{{ block.super }}
<script>
  $(document).ready(function () {
    base_url = "{% url 'kitchen_display:data' %}";

    tableOptions = {
      pageLength: 25,
      columnDefs: [
        {targets: 'no-sort', orderable: false},
        {targets: 'text-center',  className: 'text-center'},
      ],
    }

  });
</script>
<script type="text/javascript" src="{% static 'js/datatable-config.js' %}"></script>
<script type="text/javascript">
  $("#companyBranch").change(function() {
    table.ajax.url(this.value).load();
  });
  $('#companyBranchClear > .datatable-clearfilter').click(function(e){
    e.preventDefault();
    table.ajax.url(base_url);
  });
</script>
{% endblock %}